function Data = importMultiYearRatingClean(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DATA = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  DATA = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  Data = importfile("C:\Users\marsh\Dropbox\External\Academics\Columbia\Jan2022_EnterpriseRiskMgt\Projects\Project_LeverageRatio\MultiYearRating_Clean.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Jun-2022 17:40:35

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 63);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["x", "Company_Name", "ExchangeTicker", "Industry", "Rating", "Mean_TEV_BV", "LOG_Mean_TEV_BV", "TEV_BV_SD", "HiTEV_BV", "LoTEV_BV", "EBITDA_Mean", "EBITDA_SD", "LOG_EBITDA_SD", "EBITDA_SD_TEV", "LOG_EBITDA_SD_TEV", "HiEBITDA_SD", "LoEBITDA_SD", "EL_2013", "EL_2014", "EL_2015", "EL_2016", "EL_2017", "EL_2018", "EL_2019", "EL_2020", "EL_2021", "EL_2022", "Mean_EL", "EL_SD", "LM_2013", "LM_2014", "LM_2015", "LM_2016", "LM_2017", "LM_2018", "LM_2019", "LM_2020", "LM_2021", "LM_2022", "Mean_LM", "LM_SD", "BL_2013", "BL_2014", "BL_2015", "BL_2016", "BL_2017", "BL_2018", "BL_2019", "BL_2020", "BL_2021", "BL_2022", "Mean_BL", "BL_SD", "TEV_BV_2013", "TEV_BV_2014", "TEV_BV_2015", "TEV_BV_2016", "TEV_BV_2017", "TEV_BV_2018", "TEV_BV_2019", "TEV_BV_2020", "TEV_BV_2021", "TEV_BV_2022"];
opts.VariableTypes = ["double", "string", "string", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Company_Name", "ExchangeTicker"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Company_Name", "ExchangeTicker", "Industry", "Rating"], "EmptyFieldRule", "auto");

% Import the data
Data = readtable(filename, opts);

end